name: 'Setup Dependencies'
description: 'Installs system and Python dependencies for the project using build.py'

runs:
  using: "composite"
  steps:
    - name: Install all dependencies using build.py
      shell: bash
      run: |
        python build.py --install-deps