# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master", "development" ]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: [ "master", "development" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        sudo apt-get install -y libegl1 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xvfb libxkbcommon-x11-0 portaudio19-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest (in xvfb)
#      run: |
#        xvfb-run -a pytest
    - name: Test with pytest (no xvfb)
      run: |
        pytest

  build:
    needs: test
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: macos-latest # x64 runner
            arch: x64
          - os: macos-14 # arm64 runner for Apple Silicon
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up QEMU
      if: matrix.arch == 'arm64' && startsWith(matrix.os, 'ubuntu')
      uses: docker/setup-qemu-action@v3

    - name: Create Release
      id: create_release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_gui.txt
        pip install cx_freeze

    - name: Build with cx_Freeze
      run: python setup.py build

    - name: Determine Build Path and Archive Name
      id: build_info
      shell: bash
      run: |
        BUILD_DIR=$(find build -maxdepth 1 -type d -name 'exe.*' -print -quit)
        if [[ -z "$BUILD_DIR" ]]; then
          echo "Build directory not found!"
          exit 1
        fi
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_OUTPUT

        ref_name="${{ github.ref_name }}"
        ref_name_sanitized="${ref_name//\//-}"

        if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
          VERSION_NAME="$ref_name_sanitized"
        else
          VERSION_NAME="$ref_name_sanitized-${{ github.sha }}"
        fi

        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          ARCHIVE_NAME="mp3-tag-rebuilder-$VERSION_NAME-${{ matrix.os }}-${{ matrix.arch }}.zip"
          echo "ASSET_CONTENT_TYPE=application/zip" >> $GITHUB_OUTPUT
        else
          ARCHIVE_NAME="mp3-tag-rebuilder-$VERSION_NAME-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
          echo "ASSET_CONTENT_TYPE=application/gzip" >> $GITHUB_OUTPUT
        fi
        echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_OUTPUT

    - name: Archive Build Artifacts (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        cd ${{ steps.build_info.outputs.BUILD_DIR }}
        Compress-Archive -Path * -DestinationPath ${{ github.workspace }}/${{ steps.build_info.outputs.ARCHIVE_NAME }}

    - name: Archive Build Artifacts (Linux/macOS)
      if: matrix.os != 'windows-latest'
      shell: bash
      run: tar czf ${{ steps.build_info.outputs.ARCHIVE_NAME }} -C ${{ steps.build_info.outputs.BUILD_DIR }} .

    - name: Upload Build Artifact
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build_info.outputs.ARCHIVE_NAME }}
        path: ${{ steps.build_info.outputs.ARCHIVE_NAME }}

    - name: Upload Release Asset
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.build_info.outputs.ARCHIVE_NAME }}
        asset_name: ${{ steps.build_info.outputs.ARCHIVE_NAME }}
        asset_content_type: ${{ steps.build_info.outputs.ASSET_CONTENT_TYPE }}
